name: CI

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v7 # download the repo code
      - uses: actions/setup-node@v7 # install Node.js
        with:
          node-version: 22
      - run: npm ci # install exact versions from package-lock.json
      - run: npm run lint # ESLint
      - run: npm run format:check # Prettier
      - run: npm run build # make sure the app compiles
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7 # download the repo code

      - name: Set up python
        uses: actions/setup-python@v5 # install Python
        with:
          python-version: "3.12"

      - name: Install uv # install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --dev # install dependencies from pyproject.toml

      - name: Run ruff
        run: uv run ruff check . # run ruff

      - name: Check formatting with ruff
        run: uv run ruff format --check . # check formatting

      - name: Run tests
        run: uv run pytest # run tests with pytest
